Refactor component to use new token structure
selsa-inube/inubekit-countdownbar pull request #3
Opened 2024-03-06 17:05 UTC by cmarin001

This pull request encompasses a comprehensive refactor of a `<CountdownBar>`  within our application to align it with a newly introduced token structure. This strategic update is aimed at enhancing the component's design consistency, scalability, and maintainability by leveraging the advanced capabilities provided by the new design tokens.

2024-03-06 18:37 UTC, JanuarAsprilla commented on src/CountdownBar/CountdownBar.stories.tsx
>  import { CountdownBar, ICountdownBarProps } from ".";
change `ICountdownBarProps` to `ICountdownBar`.
make this change wherever that interface is located

2024-03-06 19:04 UTC, cmarin001 commented on src/CountdownBar/CountdownBar.stories.tsx
>  import { CountdownBar, ICountdownBarProps } from ".";
solved

2024-03-06 19:32 UTC, JanuarAsprilla approved these changes

2024-03-07 03:00 UTC, wfercanas requested changes

2024-03-07 15:01 UTC, cmarin001 commented on src/CountdownBar/props.ts
> +type Appearance = typeof appereances;
solved

2024-03-07 18:59 UTC, wfercanas requested changes

2024-03-07 18:59 UTC, wfercanas commented on src/CountdownBar/props.ts
> +type Appearance = typeof appereances;
You're missing `(typeof appearances)[number]`

2024-03-07 19:07 UTC, wfercanas approved these changes

2024-03-07 19:07 UTC, merged